DROP TABLE IF EXISTS CARD;
CREATE TABLE CARD(ID BIGINT PRIMARY KEY auto_increment, WORD VARCHAR(4000));
INSERT INTO CARD(word) VALUES('Hello');
INSERT INTO CARD(word) VALUES('World');
INSERT INTO CARD(word) VALUES('And');
INSERT INTO CARD(word) VALUES('good day');

